// Top Canadian cities and towns
const CANADIAN_CITIES = [
  "Toronto","Montreal","Vancouver","Calgary","Edmonton","Ottawa","Winnipeg","Quebec City",
  "Hamilton","Kitchener","London","Victoria","Halifax","Oshawa","Windsor","Saskatoon",
  "Regina","Sherbrooke","St. John's","Barrie","Kelowna","Abbotsford","Kingston","Sudbury",
  "Saguenay","Trois-Rivières","Guelph","Moncton","Brantford","Saint John","Thunder Bay",
  "Nanaimo","Chatham","Welland","Sarnia","Red Deer","Lethbridge","Kamloops","Prince George",
  "Medicine Hat","Chilliwack","Belleville","Peterborough","Sault Ste. Marie","Orangeville",
  "Brampton","Mississauga","Markham","Richmond Hill","Vaughan","Oakville","Burlington",
  "Milton","Ajax","Whitby","Pickering","Newmarket","Aurora","Georgina","Innisfil","Collingwood",
  "Owen Sound","Midland","Orillia","Gravenhurst","Bracebridge","Huntsville","North Bay",
  "Timmins","Kirkland Lake","Elliot Lake","Espanola","Parry Sound","Pembroke","Petawawa",
  "Renfrew","Arnprior","Carleton Place","Perth","Smiths Falls","Brockville","Cornwall",
  "Hawkesbury","Rockland","Orleans","Kanata","Stittsville","Nepean","Gloucester","Gatineau",
  "Laval","Longueuil","Brossard","Saint-Jean-sur-Richelieu","Drummondville","Granby",
  "Shawinigan","Victoriaville","Rimouski","Rouyn-Noranda","Val-d'Or","Sept-Îles","Baie-Comeau",
  "Fredericton","Dieppe","Miramichi","Bathurst","Riverview","Edmundston","Campbellton",
  "Truro","Sydney","New Glasgow","Amherst","Bridgewater","Yarmouth","Kentville","Antigonish",
  "Charlottetown","Summerside","Stratford","Cornwallis Park","Alberton","Souris",
  "Whitehorse","Yellowknife","Iqaluit","Dawson City","Watson Lake","Fort Smith","Hay River",
  "Airdrie","St. Albert","Sherwood Park","Spruce Grove","Leduc","Fort Saskatchewan",
  "Lloydminster","Grande Prairie","Fort McMurray","Cold Lake","Camrose","Wetaskiwin",
  "Sylvan Lake","Cochrane","Okotoks","Chestermere","Strathmore","Brooks","Drumheller",
  "Canmore","Banff","High River","Claresholm","Taber","Coaldale","Cardston","Pincher Creek",
  "Cranbrook","Penticton","Vernon","Courtenay","Campbell River","Port Alberni","Duncan",
  "Langford","Colwood","Saanich","Oak Bay","Esquimalt","Parksville","Qualicum Beach",
  "Squamish","Whistler","Hope","Mission","Maple Ridge","Langley","Surrey","Burnaby",
  "Coquitlam","Port Coquitlam","Port Moody","New Westminster","Delta","White Rock",
  "Prince Rupert","Terrace","Kitimat","Smithers","Williams Lake","Quesnel","100 Mile House",
  "Merritt","Revelstoke","Golden","Fernie","Trail","Castlegar","Nelson","Grand Forks",
  "Moose Jaw","Prince Albert","North Battleford","Weyburn","Estevan","Swift Current",
  "Yorkton","Melfort","Humboldt","Kindersley","Melville","Battleford","Meadow Lake",
  "La Ronge","Flin Flon","Thompson","Portage la Prairie","Brandon","Steinbach","Selkirk",
  "Winkler","Morden","Dauphin","The Pas","Swan River","Virden","Neepawa","Carman"
].sort();

// Top Canadian retailers
const CANADIAN_RETAILERS = [
  "Amazon","Apple Store","Atmosphere","Bass Pro Shops","Bath & Body Works",
  "Best Buy","Books & Beyond","Bootlegger","Browns Shoes","Canadian Tire",
  "Chapters Indigo","Cineplex","Claire's","Clarks","Costco","Curves",
  "Dollarama","Dollar Tree","Durham Tire","EB Games","Express",
  "FGL Sports","Food Basics","Forever 21","GameStop","Giant Tiger",
  "H&M","Home Depot","Home Hardware","Home Outfitters","Home Sense",
  "Homesense","Hudson's Bay","IKEA","Indigo","Inspirations",
  "Kitchen Stuff Plus","Kumon","Laura","Le Château","Leons",
  "LinenChest","Loblaws","London Drugs","Lowe's","Lululemon",
  "Mark's","Marshall's","Metro","Michael's","Mountain Equipment Co-op",
  "No Frills","Nordstrom","Old Navy","Otter Co-op","Penningtons",
  "Pet Smart","Petro-Canada","Pier 1","Princess Auto","Reitmans",
  "Rexall","Roots","Rona","Safeway","Salvation Army",
  "Sephora","Shoppers Drug Mart","Sleep Country","Sobeys","Sport Chek",
  "Sportchek","Staples","The Bay","The Source","Thrift Store",
  "Tim Hortons","TJX","Toys R Us","Value Village","Walmart",
  "Wholesale Club","Winners","Zara","Zumiez"
].sort();
